// <auto-generated />
namespace WorkoutDiary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateWorkoutnewProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateWorkoutnewProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "202101130905405_updateWorkout-newProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
